# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-01-02T20:27:50Z"
  generation: 1
  labels:
    app: jackett
  name: jackett
  namespace: plexserver
  resourceVersion: "986368"
  uid: a1ed3ef4-7bb9-4abd-9b25-c757253e09b1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jackett
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jackett
    spec:
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pv-claim-storage
      - name: pv-config
        persistentVolumeClaim:
          claimName: pv-claim-config
      containers:
      - image: linuxserver/jackett
        imagePullPolicy: Always
        name: jackett
        volumeMounts:
          - mountPath: "/media"
            name: pv-storage
          - mountPath: "/config"
            name: pv-config
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-02T20:29:37Z"
    lastUpdateTime: "2022-01-02T20:29:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-02T20:27:54Z"
    lastUpdateTime: "2022-01-02T20:29:37Z"
    message: ReplicaSet "jackett-6b9b7d8bdd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
