apiVersion: v1
kind: PersistentVolume
metadata:
  claimRef:
  name: pv-volume-config
  namespace: plexserver
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media/down/plex/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-storage
  namespace: plexserver
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media"
