apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-config
  namespace: plexserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-storage
  namespace: plexserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
