# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-01-02T20:29:04Z"
  generation: 1
  labels:
    app: sonarr
  name: sonarr
  namespace: plexserver
  resourceVersion: "987045"
  uid: a76bea19-1f34-4569-a36a-8abb9790bb70
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sonarr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sonarr
    spec:
      nodeName: k3s-master-01
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pv-claim-storage
      - name: pv-config
        persistentVolumeClaim:
          claimName: pv-claim-config
      containers:
      - image: linuxserver/sonarr
        imagePullPolicy: Always
        name: sonarr
        volumeMounts:
          - mountPath: "/media"
            name: pv-storage
          - mountPath: "/config"
            name: pv-config
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-02T20:35:33Z"
    lastUpdateTime: "2022-01-02T20:35:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-02T20:29:07Z"
    lastUpdateTime: "2022-01-02T20:35:33Z"
    message: ReplicaSet "sonarr-98757dc67" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
